# variables
@baseUrl = http://localhost:3000

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create a room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Room 1",
  "description": "This is a test room"
}

###

# @roomId = {{getRooms.response.body.$.[4].id}}
@roomId = {{createRoom.response.body.$.id}}
###

# Get room`s questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create questions
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "O que é drizzle?"
}